## https://docs.streamlit.io/knowledge-base/tutorials/databases/snowflake
[snowflake_ms_lab_temp_check]
user = "XXX"
password = ""
account = "oj65307"
region = "eu-west-1"
authenticator = "externalbrowser"
warehouse = "LAB_MULTISTRAT_ANALYTICS_WH"
database = "LAB_MULTISTRAT_ANALYTICS"
schema = "XXX"
